# Generated by Django 5.2.4 on 2025-07-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfchunk',
            name='source_file',
            field=models.CharField(default='banglaboi.pdf', max_length=255),
        ),
    ]
